import os
from app.database import SessionLocal
from sqlalchemy import text, inspect
from datetime import datetime

db = SessionLocal()
rpt = []
def log(s=""): rpt.append(str(s))

log("# Framework 1-A Validation Report (FINAL) - 2026-08-18")
log("")
log("**Validated by:** Qwen (PM/Data QA)")
log(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
log("")
log("## Strategic Decision (PO)")
log("> با همین اطلاعات فعلی کار را پیش میبریم. تصویر بارکد و اطلاعات جزئی در نسخه بعدی اضافه میشود.")
log("")

products = [
    ("Product A", "ISDIN-FUSION-WATER-MAGIC-50"),
    ("Product B", "ISDIN-FOTOULTRA-ACTIVE-UNIFY-COLOR-50")
]

inspector = inspect(db.get_bind())
tables = inspector.get_table_names()
target_tables = [t for t in tables if 'product_id' in [c['name'] for c in inspector.get_columns(t)]]

log(f"## Database Scan: Found {len(target_tables)} table(s) with 'product_id': {', '.join(target_tables) if target_tables else 'NONE'}")
log("")

for p_name, pid in products:
    log(f"### {p_name}: `{pid}`")
    log("")
    log("| Field | Value | Status |")
    log("|---|---|---|")
    
    filled = 0
    missing = []
    found_data = False
    best_row = None
    best_cols = []
    
    for t in target_tables:
        try:
            res = db.execute(text(f"SELECT * FROM {t} WHERE product_id = '{pid}'")).fetchone()
            if res:
                found_data = True
                best_row = res._mapping
                best_cols = [c['name'] for c in inspector.get_columns(t)]
                break
        except:
            pass
            
    if not found_data:
        log("*Source: NOT FOUND in any table*")
        log("")
        for f in ["product_id", "brand", "canonical_name", "variant", "size_unit", "barcode_gtin", "market_region", "packaging_version", "inventory_confirmation", "inventory_confirmation_date"]:
            log(f"| {f} | UNKNOWN |  MISSING |")
            missing.append(f)
    else:
        log(f"*Source: `{best_cols[0]}` table*")
        log("")
        target_fields = ["product_id", "brand", "canonical_name", "variant", "size_unit", "barcode_gtin", "market_region", "packaging_version", "inventory_confirmation", "inventory_confirmation_date"]
        for f in target_fields:
            if f in best_cols:
                val = best_row.get(f)
                if val:
                    log(f"| {f} | {str(val)[:40]} |  PRESENT |")
                    filled += 1
                else:
                    log(f"| {f} | UNKNOWN |  MISSING |")
                    missing.append(f)
            else:
                log(f"| {f} | N/A (col missing) |  MISSING |")
                missing.append(f)
                
    verdict = "IDENTIFIED" if filled == 10 else ("PARTIALLY_IDENTIFIED" if filled >= 5 else "UNIDENTIFIED")
    log("")
    log(f"**VERDICT: {verdict}** ({filled}/10 fields)")
    log("")

log("## Unknown Register (Framework 5)")
log("| Field | Products | Severity | Reason |")
log("|---|---|---|---|")
log("| barcode_gtin | A, B | MEDIUM | Awaiting accounting system (PO decision) |")
log("| inventory_confirmation | A, B | HIGH | Awaiting accounting system |")
log("| inventory_confirmation_date | A, B | HIGH | Awaiting accounting system |")
log("")
log("---")
log("*Report auto-generated by Qwen (PM/Data QA)*")

os.makedirs("docs/reports", exist_ok=True)
with open("docs/reports/framework-1-a-validation-final.md", "w", encoding="utf-8") as f:
    f.write("\n".join(rpt))

print(" SUCCESS: Report saved to docs/reports/framework-1-a-validation-final.md")
db.close()
