"""make_reports.py — Create final reports safely"""
from pathlib import Path

P = Path("E:/HBI")

# 1. Remove wrongly-named file
wrong = P / "docs09_gate_reportsGATE_PRODUCTION_READINESS.md"
if wrong.exists():
    wrong.unlink()
    print("[DEL] " + wrong.name)

# 2. Create reports directory
rd = P / "docs" / "09_gate_reports"
rd.mkdir(parents=True, exist_ok=True)

# 3. FINAL PROJECT REPORT
r = []
r.append("# HBI PROJECT - FINAL REPORT")
r.append("")
r.append("**Date:** 2026-08-15")
r.append("**Owner:** Engineer Maqsoudi")
r.append("**Prepared by:** Qwen (Project Manager / Data QA)")
r.append("**Status:** MVP COMPLETE - E2E VERIFIED")
r.append("")
r.append("---")
r.append("")
r.append("## 1. Executive Summary")
r.append("")
r.append("HBI (Health & Beauty Intelligence) Phase 1 has reached a functional MVP state.")
r.append("The complete pipeline from Customer to Recommendation has been implemented,")
r.append("tested, and verified on the real database.")
r.append("")
r.append("Key achievements:")
r.append("- Schema Lock v1.1 enforced")
r.append("- MatchScoringEngine implemented per Architecture Freeze v0.1 (AD-1, AD-2)")
r.append("- AD-3 Recommendation Contract fully mapped in DTO/Facade")
r.append("- Evidence for Products A & B (ISDIN) injected and QA-validated")
r.append("- E2E test on real DB: 6/6 PASS")
r.append("")
r.append("---")
r.append("")
r.append("## 2. Git History (verified)")
r.append("")
r.append("```")
r.append("9ee4dd3 feat(contract): map AD-3 fields in _to_recommendation_dto")
r.append("3cda23b feat(contract): add AD-3 fields to RecommendationDTO")
r.append("9c1b583 fix(scoring): add evidence_score to Recommendation creation")
r.append("d3ba760 chore: organize repo")
r.append("8f86288 feat(scoring): integrate MatchScoringEngine")
r.append("db47698 feat(scoring): MatchScoringEngine + 7 tests")
r.append("14eaf0b feat(scoring): add scoring_constants per AD-1,AD-2")
r.append("b38bce4 initialize HBI memory structure")
r.append("```")
r.append("")
r.append("---")
r.append("")
r.append("## 3. Architecture Decisions (Frozen)")
r.append("")
r.append("| ID | Decision | Status |")
r.append("|----|----------|--------|")
r.append("| AD-1 | Scoring Weights (Need 0.50, Evidence 0.30, Inventory 0.20) | FROZEN |")
r.append("| AD-2 | Confidence Formula (0.4*need + 0.6*evidence) + Thresholds | FROZEN |")
r.append("| AD-3 | Recommendation Contract (9 fields) | IMPLEMENTED |")
r.append("| AD-4 | Hard Gates (evidence=0 or inventory=0 -> NEEDS_REVIEW) | IMPLEMENTED |")
r.append("")
r.append("---")
r.append("")
r.append("## 4. Evidence Package (Products A & B)")
r.append("")
r.append("| Product | Claims | VERIFIED | NEEDS_REVIEW | evidence_score |")
r.append("|---------|--------|----------|--------------|----------------|")
r.append("| A: ISDIN-FUSION-WATER-MAGIC-50 | 6 | 4 | 2 | 0.6 |")
r.append("| B: ISDIN-FOTOULTRA-ACTIVE-UNIFY-COLOR-50 | 6 | 4 | 2 | 0.6 |")
r.append("")
r.append("All sources: OFFICIAL_MANUFACTURER (ISDIN UK product pages).")
r.append("")
r.append("---")
r.append("")
r.append("## 5. E2E Test Results")
r.append("")
r.append("**Test:** tests/test_e2e_real.py")
r.append("**Result:** 6/6 PASS")
r.append("**DB:** data/hbi.db (real, with PRAGMA foreign_keys=ON)")
r.append("")
r.append("Steps verified:")
r.append("1. Customer creation (consent_to_store_data=1)")
r.append("2. Case creation (reasoning_status=OPEN)")
r.append("3. Recommendation generation (2 products scored)")
r.append("4. Persistence in DB")
r.append("5. Cleanup")
r.append("")
r.append("---")
r.append("")
r.append("## 6. Known Issues & Risks")
r.append("")
r.append("| Issue | Severity | Status |")
r.append("|-------|----------|--------|")
r.append("| Products C & D UNIDENTIFIED | MEDIUM | SKIPPED BY PO DECISION |")
r.append("| barcode_gtin UNKNOWN for A & B | MEDIUM | NEEDS_REVIEW |")
r.append("| availability/price not mapped in DTO | LOW | DEFERRED |")
r.append("")
r.append("---")
r.append("")
r.append("## 7. Next Steps (Recommended)")
r.append("")
r.append("1. Obtain physical info for Products C & D from PO")
r.append("2. Obtain barcode_gtin for Products A & B")
r.append("3. Map availability and price in Facade (requires Inventory query)")
r.append("4. Add independent Evidence sources (REGULATORY, PEER_REVIEWED)")
r.append("5. Production deployment planning")
r.append("")
r.append("---")
r.append("")
r.append("*Generated on 2026-08-15*")

rp = rd / "FINAL_PROJECT_REPORT.md"
rp.write_text("\n".join(r), encoding="utf-8")
print("[CREATE] " + str(rp.relative_to(P)))

# 4. PRODUCTION READINESS GATE
g = []
g.append("# GATE: PRODUCTION READINESS")
g.append("")
g.append("**Date:** 2026-08-15")
g.append("**Authority:** Engineer Maqsoudi (PO)")
g.append("**Prepared by:** Qwen (Data QA)")
g.append("")
g.append("---")
g.append("")
g.append("## Verdict")
g.append("")
g.append("```")
g.append("CONDITIONALLY READY FOR PRODUCTION READINESS REVIEW")
g.append("```")
g.append("")
g.append("---")
g.append("")
g.append("## Checklist")
g.append("")
g.append("| Item | Status | Evidence |")
g.append("|------|--------|----------|")
g.append("| Schema Lock v1.1 | PASS | GATE 5 approved |")
g.append("| Backend Models | PASS | Baseline tests |")
g.append("| MatchScoringEngine | PASS | 7/7 unit tests |")
g.append("| AD-3 Contract | PASS | 16 fields in DTO |")
g.append("| Evidence A & B | PASS | 12 claims injected |")
g.append("| E2E on Real DB | PASS | 6/6 |")
g.append("| Persistence | PASS | Verified |")
g.append("| Git History | PASS | 8 real commits |")
g.append("| Consent (AD) | PASS | consent_to_store_data |")
g.append("")
g.append("---")
g.append("")
g.append("## Conditions (must be met before full production)")
g.append("")
g.append("1. Products C & D must be IDENTIFIED or explicitly deferred by PO")
g.append("2. barcode_gtin for A & B must be provided or marked as accepted risk")
g.append("3. availability and price mapping must be completed")
g.append("4. Independent Evidence source (REGULATORY) recommended for at least one claim per product")
g.append("")
g.append("---")
g.append("")
g.append("## Blockers")
g.append("")
g.append("**None.** All critical blockers have been resolved.")
g.append("")
g.append("---")
g.append("")
g.append("## Escalation")
g.append("")
g.append("- Products C & D: PO decision required")
g.append("- barcode_gtin: PO to provide physical product info")
g.append("")
g.append("---")
g.append("")
g.append("*Generated on 2026-08-15*")

gp = rd / "GATE_PRODUCTION_READINESS.md"
gp.write_text("\n".join(g), encoding="utf-8")
print("[CREATE] " + str(gp.relative_to(P)))

print("\nDone. Now run git commands.")