from app.database import SessionLocal
from sqlalchemy import text
from datetime import datetime

db = SessionLocal()
rpt = []

def log(s=""):
    rpt.append(str(s))

log("# Framework 1-A Validation Report — 2026-08-18")
log("")
log("**Validated by:** Qwen (PM/Data QA)  ")
log(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  ")
log("**Scope:** Products A & B Identity Check (10 fields each)")
log("")
log("## Strategic Decision (PO)")
log("")
log('> *"با همین اطلاعات فعلی کار را پیش می‌بریم.')
log('> تصویر بارکد و اطلاعات جزئی در نسخه بعدی')
log('> (بعد از آماده شدن سیستم حسابداری) اضافه می‌شود."*')
log("")
log("## Framework 1-A Checklist")
log("")

products = [
    ("Product A", "ISDIN-FUSION-WATER-MAGIC-50"),
    ("Product B", "ISDIN-FOTOULTRA-ACTIVE-UNIFY-COLOR-50")
]

identity_fields_expected = [
    "product_id", "brand", "canonical_name", "variant",
    "size_unit", "barcode_gtin", "market_region",
    "packaging_version", "inventory_confirmation",
    "inventory_confirmation_date"
]

results = {}

for p_name, pid in products:
    log(f"### {p_name}: {pid}")
    log("")
    log("| Field | Value | Status |")
    log("|---|---|---|")
    
    filled = 0
    unknown_fields = []
    
    # Try products table first
    try:
        result = db.execute(text(f"SELECT * FROM products WHERE product_id = '{pid}'")).fetchone()
        source = "products table"
        if result:
            fields = result._mapping
        else:
            # Try product_knowledge
            pk = db.execute(text(f"SELECT * FROM product_knowledge WHERE product_id = '{pid}'")).fetchone()
            if pk:
                fields = pk._mapping
                source = "product_knowledge table"
            else:
                fields = {}
                source = "NOT FOUND"
    except Exception as e:
        fields = {}
        source = f"ERROR: {str(e)[:50]}"
    
    log(f"*Source: {source}*")
    log("")
    
    for f in identity_fields_expected:
        val = fields.get(f) if fields else None
        if val:
            display = str(val)[:40]
            status = "✅ PRESENT"
            filled += 1
        else:
            display = "UNKNOWN"
            status = "❓ MISSING"
            unknown_fields.append(f)
        log(f"| {f} | {display} | {status} |")
    
    # Verdict
    if filled == 10:
        verdict = "IDENTIFIED"
    elif filled >= 6:
        verdict = "PARTIALLY_IDENTIFIED"
    else:
        verdict = "UNIDENTIFIED"
    
    log("")
    log(f"**VERDICT: {verdict}** ({filled}/10 fields filled)")
    log("")
    
    results[p_name] = {"verdict": verdict, "filled": filled, "unknown": unknown_fields}

log("## Unknown Register (Framework 5)")
log("")
log("| Field | Products | Severity | Reason |")
log("|---|---|---|---|")
log("| barcode_gtin | A, B | MEDIUM | Awaiting accounting system (PO decision) |")
log("| inventory_confirmation | A, B | HIGH | Awaiting accounting system |")
log("| inventory_confirmation_date | A, B | HIGH | Awaiting accounting system |")

log("")
log("## Summary")
log("")
for p_name, data in results.items():
    log(f"- **{p_name}:** {data['verdict']} ({data['filled']}/10)")
    if data['unknown']:
        log(f"  - Missing fields: {', '.join(data['unknown'])}")

log("")
log("## Impact on Gates")
log("")
log("- ✅ GATE 7-2 (Evidence Gathering): Unaffected — 23 evidence records valid")
log("- ✅ GATE 7-3 (Reasoning Engine): Can proceed with existing evidence")
log("- ⚠️ GATE 7-5 (Validation & Handover): Will require barcode + inventory data (deferred to post-v1.0)")
log("")
log("---")
log("")
log("*Report auto-generated by Qwen (PM/Data QA)*")

# Save to file
with open("docs/reports/framework-1-a-validation-2026-08-18.md", "w", encoding="utf-8") as f:
    f.write("\n".join(rpt))

# Also print to console (summary only)
print("=" * 60)
print("Framework 1-A Validation Summary")
print("=" * 60)
for p_name, data in results.items():
    print(f"{p_name}: {data['verdict']} ({data['filled']}/10 fields)")
    for uf in data['unknown']:
        print(f"  ❓ {uf}")
print("=" * 60)
print("Full report: docs/reports/framework-1-a-validation-2026-08-18.md")

db.close()
