#Requires -Version 5.1
<#
.SYNOPSIS
  HBI PO One-Paste Safe Write — durable path when AI Write is offline.
.NOTES
  - Fill the variables in the CONFIG section only.
  - Paste entire script once in PowerShell from E:\hbi (or set $RepoRoot).
  - Does NOT put token in remote URL.
  - Does NOT forge git user.name to an AI.
  - Author = whatever git is already configured as on this machine (PO).
  Generated by Grok1, Reviewed by PO, Executed by PO
#>
$ErrorActionPreference = "Stop"

# ========== CONFIG (edit only these) ==========
$RepoRoot     = "E:\hbi"
$GitHubPath   = "docs/example_from_member.md"   # relative path in repo
$CommitMsg    = "docs: example (Generated by DeepSeek2, Reviewed by Qwen1, Executed by PO)"
# Paste full file body between @' and '@ below (keep quotes as-is)
$FileContent  = @'
# replace this body with member file content
'@
# ==============================================

Set-Location $RepoRoot

Write-Host "=== HBI PO One-Paste Safe Write ===" -ForegroundColor Cyan
Write-Host "Repo: $RepoRoot"

# 1) Remote HEAD check + pull
$remoteBefore = (git rev-parse origin/master 2>$null)
if (-not $remoteBefore) { git fetch origin master 2>$null | Out-Null; $remoteBefore = git rev-parse origin/master }
Write-Host "origin/master before: $remoteBefore"
git pull --ff-only origin master
if ($LASTEXITCODE -ne 0) {
    Write-Host "PULL FAILED — fix conflicts or network, then retry. No write done." -ForegroundColor Red
    exit 1
}

# 2) Worktree check (warn only if dirty outside target)
$status = git status --porcelain
if ($status) {
    Write-Host "WARNING: dirty worktree:" -ForegroundColor Yellow
    Write-Host $status
    Write-Host "Continue only if you accept mixing changes. Ctrl+C to abort."
    Start-Sleep -Seconds 3
}

# 3) Write file
$full = Join-Path $RepoRoot ($GitHubPath -replace '/', '\')
$dir = Split-Path -Parent $full
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
# Backup if exists
if (Test-Path $full) {
    $bak = "$full.bak_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
    Copy-Item $full $bak -Force
    Write-Host "Backup: $bak"
}
Set-Content -Path $full -Value $FileContent -Encoding utf8
Write-Host "Wrote: $GitHubPath"

# 4) Diff review (auto-show; human already approved by running script)
git add -- $GitHubPath
git diff --cached --stat
git diff --cached
Write-Host "Committing in 2s... Ctrl+C to abort" -ForegroundColor Yellow
Start-Sleep -Seconds 2

# 5) Commit (real machine user — do not override to AI name)
git commit -m $CommitMsg
if ($LASTEXITCODE -ne 0) {
    Write-Host "COMMIT failed or empty" -ForegroundColor Red
    exit 1
}
$localSha = git rev-parse HEAD
Write-Host "LOCAL SHA: $localSha"

# 6) Push
git push origin master
if ($LASTEXITCODE -ne 0) {
    Write-Host "PUSH failed" -ForegroundColor Red
    exit 1
}

# 7) Remote verify
git fetch origin master
$remoteAfter = git rev-parse origin/master
Write-Host "origin/master after: $remoteAfter"
if ($remoteAfter -ne $localSha) {
    Write-Host "VERIFY FAIL: local SHA != origin/master" -ForegroundColor Red
    exit 1
}
Write-Host "VERIFY OK: remote has $remoteAfter" -ForegroundColor Green
Write-Host "Next: open https://github.com/vahidmaghsoudi2/hbi/actions and confirm run on this SHA"
Write-Host "=== DONE ===" -ForegroundColor Green
