"""
scoring_constants.py — Architecture Freeze v0.1
مطابق AD-1 تا AD-4 مصوب توسط Architecture Authority
"""

# ===== AD-1: Scoring Weights (Final Score) =====
SCORE_WEIGHT_NEED = 0.50
SCORE_WEIGHT_EVIDENCE = 0.30
SCORE_WEIGHT_INVENTORY = 0.20

# ===== AD-2: Confidence Formula =====
CONFIDENCE_WEIGHT_NEED = 0.40
CONFIDENCE_WEIGHT_EVIDENCE = 0.60

# ===== AD-2: Thresholds =====
THRESHOLD_ELIGIBLE = 0.70
THRESHOLD_NEEDS_REVIEW = 0.50

# ===== AD-2: Hard Gate =====
HARD_GATE_EVIDENCE_MIN = 0.0
HARD_GATE_INVENTORY_MIN = 0.0

# ===== Evidence Source Weights (Framework 1.B) =====
EVIDENCE_WEIGHT_INDEPENDENT = 1.0   # PEER_REVIEWED, CLINICAL_TRIAL, REGULATORY
EVIDENCE_WEIGHT_MANUFACTURER = 0.6   # OFFICIAL_MANUFACTURER, MANUFACTURER
EVIDENCE_WEIGHT_RETAILER = 0.4       # REPUTABLE_RETAILER
EVIDENCE_WEIGHT_SECONDARY = 0.2      # SECONDARY
EVIDENCE_WEIGHT_NONE = 0.0           # UNVERIFIED

# ===== Inventory Score =====
INVENTORY_SCORE_AVAILABLE = 1.0
INVENTORY_SCORE_LIMITED = 0.5
INVENTORY_SCORE_UNAVAILABLE = 0.0

# ===== Eligibility Statuses =====
ELIGIBILITY_ELIGIBLE = "ELIGIBLE"
ELIGIBILITY_NEEDS_REVIEW = "NEEDS_REVIEW"
ELIGIBILITY_INELIGIBLE = "INELIGIBLE"

# ===== Evidence Statuses =====
EVIDENCE_STATUS_VERIFIED = "VERIFIED"
EVIDENCE_STATUS_UNVERIFIED = "UNVERIFIED"

# ===== Warnings =====
WARNING_HARD_GATE_ACTIVE = "HARD_GATE_ACTIVE"
WARNING_EVIDENCE_MISSING = "EVIDENCE_MISSING"
WARNING_INVENTORY_UNAVAILABLE = "INVENTORY_UNAVAILABLE"